package com.inshort.be.transfer;

public enum RiskSignal {
  LARGE_AMOUNT,
  NEW_RECIPIENT,
  DAILY_ACCUMULATION,
  NEAR_DAILY_LIMIT,
  RAPID_TRANSFERS,
  SPLIT_TRANSFER,
  RECENT_HIGH_RISK_RECIPIENT,
  PIN_CONFIRMATION_FAILED
}
